import { SettingsContextProvider } from '@/Context/SettingsContext'
import './globals.css'
import type { Metadata } from 'next'
import { RulesContextProvider } from '@/Context/RulesContext'
import { ModeTypeProvider } from '@/Context/ModeContext'
import Score from '@/components/Score'
import Options from '@/components/Options'
import { GameProvider } from '@/Context/GameContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SettingsContextProvider>
          <RulesContextProvider>
            <ModeTypeProvider>
              <GameProvider>
              {children}
              </GameProvider>
        </ModeTypeProvider>
        </RulesContextProvider>
        </SettingsContextProvider>
      </body>
    </html>
  )
}
